### ISSUE TITLE
复刻项目连接数据库失败

### ISSUE THREAD

**Issue by mattheliu** [xiaoyutoua/-#1]
你好，能加一个联系方式嘛，jdbc连接不上mysql数据库

**Comment by xiaoyutoua** [comment]
可以的 2143191301我的qq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoyutoua/Recipe-management-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月8日(星期四) 中午11:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaoyutoua/Recipe-management-system] 复刻项目连接数据库失败 (Issue #1)





 
你好，能加一个联系方式嘛，jdbc连接不上mysql数据库

**Comment by mattheliu** [comment]
已经解决
